name: Archive Old Tasks

on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  archive-tasks:
    runs-on: ubuntu-latest
    
    steps:
      - name: Archive completed tasks
        run: |
          curl -X POST https://testing-cron-jobs-nextjs.vercel.app/api/tasks/archive